update code 2

diff --git a/scripts/atsrun-new b/scripts/atsrun-new
--- a/scripts/atsrun-new
+++ b/scripts/atsrun-new
@@ -68,7 +68,7 @@ ask_user() {
 local answer
 while true
   do
-    read answer
+    read -r answer
     case $answer in [Yy]* ) return 0 ;;
                     [Nn]* ) return 1 ;;
                         * ) echo "Enter y or n";;
@@ -146,39 +146,90 @@ echo -e "${LIGHTBLUE}Starting Translate${NC} ${YELLOW}[$filename]${NC}\n"
 
 
 control-autosub () {
-	echo -e "${LIGHTCYAN}Skip using Audio Process?${NC}"
-	if ! ask_user ;then
+clear
+echo -e "${LIGHTCYAN}Skip using Audio Process?${NC}"
+if ! ask_user ;then
 	continuous
-	else
+else
 	echo -e "\n${LIGHTBLUE}Confirmed skipping using Audio Process${NC}"
 	noap="yes"
-	fi
-	# Autosub all video files in the directory running the script
-	if [ $# -eq 0 ] ;then
-		echo -e "\n${GREEN}AUTOSUB ALL VIDEO FILES IN FOLDERS${NC}\n"
-		find . -type f \( -name '*.mp4' -o -name '*.mkv' -o -name '*.avi' -o -name '*.wmv' -o -name '*.ts' -o -name '*.TS' -o -name '*.mov' -o -name '*.m4v' -o -name '*.flv' \) -exec echo '{}' \; > "$HOME/listfile.txt"
-		while IFS= read -r file; do
-			if [ -f "$file" ] ;then
-				filebasename "$file"
-				## Check file Completed
-				if [ "$(grep -wF "$filename" "$autosubcomp")" == "$filename" ] 2>/dev/null ;then 
-					echo "$filename" >> "$autosubdone" 
-					echo -e "\n${YELLOW}This video file has been Autosub${NC} ${GREEN}[File]${NC}\n"
+fi
+# Autosub all video files in the directory running the script
+if [ $# -eq 0 ] ;then
+	echo -e "\n${GREEN}AUTOSUB ALL VIDEO FILES IN FOLDERS${NC}\n"
+	find . -type f \( -name '*.mp4' -o -name '*.mkv' -o -name '*.avi' -o -name '*.wmv' -o -name '*.ts' -o -name '*.TS' -o -name '*.mov' -o -name '*.m4v' -o -name '*.flv' \) -exec echo '{}' \; > "$HOME/listfile.txt"
+	while IFS= read -r file ;do
+		if [ -f "$file" ] ;then
+			filebasename "$file"
+			## Check file Completed
+			if [ "$(grep -wF "$filename" "$autosubcomp")" == "$filename" ] 2>/dev/null ;then 
+				echo "$filename" >> "$autosubdone" 
+				echo -e "\n${YELLOW}This video file has been Autosub${NC} ${GREEN}[$filename]${NC}\n"
+			else
+				config
+				! ( if [ $noap == "yes" ] ;then
+					autosub-without-ap "$file"
 				else
-					config
-					if [ $noap == "yes" ] ;then autosub-without-ap "$file" ;else autosub-with-ap "$file" ;fi
-				fi
-
-
+					! autosub-with-ap "$file" && autosub-without-ap "$file"
+				fi ) && echo -e "${RED}Autosub ${YELLOW}[$filename]${NC} fail ! Check again!${NC}" && echo "$filename" >> "$autosubfail"
+				# Run Translate Function And check Autosub Comp or Fail
+				! ( if [ -f "$filepath/$name.$S.$f" ] 2>/dev/null;then
+					Translate
+				else
+					echo -e "\n${RED}File${NC} ${YELLOW}"$name.$S.$f"${NC} ${RED}not Exist , PLEASE CHECK AGAIN${NC}\n"
+				fi ) && echo -e "${RED}Translate Subtitle ${YELLOW}[$name.$S.$f]${NC} Fail! Check again!${NC}" && echo "$filename" >> "$autosubfail"
+				# Check Video Comp or Fail to text file
+				[ -f "$filepath/$name.$f" ] 2>/dev/null && echo "$filename" >> "$autosubcomp"
 			fi
-		done < "$HOME/listfile.txt"
-	fi
+		fi
+	done < "$HOME/listfile.txt"
+	rm -f "$HOME/listfile.txt"
+else
+	echo -e "\n${GREEN}AUTOSUB CHO TUNG FILE DUOC CHON${NC}\n"
+	config
+	for file in "$@" ;do
+		# Get filename and path
+		filebasename "$file"
+		## Check file Completed
+		if [ "$(grep -wF "$filename" "$autosubcomp")" == "$filename" ] 2>/dev/null ;then 
+			echo "$filename" >> "$autosubdone" 
+			echo -e "\n${YELLOW}This video file has been Autosub${NC} ${GREEN}[$filename]${NC}\n"
+		else
+			# Running Autosub
+			! ( if [ $noap == "yes" ] ;then
+				autosub-without-ap "$file"
+			else
+				! autosub-with-ap "$file" && autosub-without-ap "$file"
+			fi ) && echo -e "${RED}Autosub ${YELLOW}[$filename]${NC} fail ! Check again!${NC}" && echo "$filename" >> "$autosubfail"
+			# Run Translate Function And check Autosub Comp or Fail
+			! ( if [ -f "$filepath/$name.$S.$f" ] 2>/dev/null;then
+				Translate
+			else
+				echo -e "\n${RED}File${NC} ${YELLOW}"$name.$S.$f"${NC} ${RED}not Exist , PLEASE CHECK AGAIN${NC}\n"
+			fi ) && echo -e "${RED}Translate Subtitle ${YELLOW}[$name.$S.$f]${NC} Fail! Check again!${NC}" && echo "$filename" >> "$autosubfail"
+			# Check Video Comp or Fail to text file
+			[ -f "$filepath/$name.$f" ] 2>/dev/null && echo "$filename" >> "$autosubcomp"
+		fi
+	done
+fi
 
+# File Da Hoan Thanh
+echo -e "\n${GREEN}[COMPLETED]${NC}\n"
+tail -n $tailnum "$autosubcomp" 2>/dev/null
+# File Khong Hoan Thanh
+if [ -f "$autosubfail" ] 2>/dev/null ;then
+	echo -e "\n${RED}[FAIL]${NC}\n"
+	cat "$autosubfail" 2>/dev/null
+	rm "$autosubfail" 2>/dev/null
+fi
+# File Da Autosub
+if [ -f "$autosubdone" ] 2>/dev/null ;then
+	echo -e "\n${YELLOW}[FAIL]${NC}\n"
+	cat "$autosubdone" 2>/dev/null
+	rm "$autosubdone" 2>/dev/null
+fi
+echo -e "\n-------------------" >> "$autosubcomp"
 }
-
-
-
-
 
 # Function List Menu
 menuAutosub() {
@@ -204,60 +255,56 @@ read -r -n 1 -s choice;
 	case $choice in
 	
 		1 )  # Autosub Japanese
-			echo -e "\n-------------------" >> "$autosubcomp"
-			clear
-			CASEautosub "$@"
+			control-autosub "$@"
 		;;
 			
 		2 )	# Autosub Chinese (Simplified, China)
-			echo -e "\n-------------------" >> "$autosubcomp"
-			clear
 			S="cmn-hans-cn"
 			src="zh-cn"
-			CASEautosub "$@"
+			control-autosub "$@"
 		;;
 			
 		3 )	# Autosub English
-			echo -e "\n-------------------" >> "$autosubcomp"
-			clear
 			S="en-us"
 			src="en"
-			CASEautosub "$@"
+			control-autosub "$@"
 		;;
 			
 		4 )	# Translate (Japanese)
-			read -n 1 -s -p -r 'Tuy Chinh ? (y/n): ' option
-			echo 
-			# Option for Custom Translate
-			if { [ "$option" == "y" ] || [ "$option" == "Y" ]; } 2>/dev/null ;then
-				read -p -r 'Ngon ngu muon dich /src? ' src1
+			echo -e "Config Language ?"
+			if ! ask_user ;then
+				for file in "$@" ;do
+					# Info for Base Name
+					filebasename "$file"
+					# Translate Subtitle
+					if ! Translate ;then
+						echo -e "${YELLOW}[$filename]${NC} ${RED}is FAIL${NC}"
+						echo -e "${RED}Please Translate Again${NC}"
+					else
+						echo -e "\n${GREEN}Translate [$filename] is DONE${NC}"
+					fi
+				done
+			else
+				# Option for Custom Translate
+				read -p -r 'Enter Video Language /src : ' src1
 				# Display list SRC Support
-				if [ -n "$(autosub -ltc | grep -i "$src1")" ] 2>/dev/null ;then
+				if [ -n "$(autosub -lsc | grep -i "$src1")" ] 2>/dev/null ;then
 					echo -e "${LIGHTBLUE}$(autosub -lsc | grep -i "$src1")${NC}\n"
-					read -p -r 'Nhap thong so "SRC" nhu tren: ' src
+					read -p -r 'Enter the "SRC Language" parameter as above /Ex: en-us : ' src
+				else
+					echo -e "${RED}Language does not exist or does not support !${NC}"
 				fi
 				echo 
-				read -p -r 'Ngon ngu muon dich sang /d? ' d1
+				read -p -r 'Enter Destination Language /d : ' d1
 				# Display list D Support
 				if [ -n "$(autosub -ltc | grep -i "$d1")" ] 2>/dev/null ;then
 					echo -e "${LIGHTBLUE}$(autosub -ltc | grep -i "$d1")${NC}\n"
-					read -p -r 'Nhap thong so "D" nhu tren: ' d
+					read -p -r 'Enter the "DST Language" parameter as above /Ex: en : ' d
+				else
+					echo -e "${RED}Language does not exist or does not support !${NC}"
 				fi
-				
 			fi
 			clear
-			for file in "$@" ;do
-			# Info for Base Name
-			filebasename "$file"
-			# Translate Subtitle
-			Translate
-			if [ "$?" -eq "0" ] 2>/dev/null ;then
-				echo -e "\n${GREEN}[$filename] is DONE${NC}"
-			else
-				echo -e "${YELLOW}[$filename]${NC} ${RED}is FAIL${NC}"
-				echo -e "${RED}Please Translate Again${NC}"
-			fi
-			done
 		;;
 			
 		5 ) # Custom
